cache:
  apt: true

language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true
  include:
    # Run PHP CodeSniffer and XMLLint against just PHP 7.1 job, even
    # though the PHPCompatibility config checks against 7.0.
    - php: 7.1
      env: SNIFF=1 LINT=1
      addons:
        apt:
          packages:
            - libxml2-utils

  allow_failures:
    # Allow failures for unstable builds
    - php: nightly

before_install:
  - export XMLLINT_INDENT="	"

install:
  - composer install

script:
  # Lint the PHP files against parse errors.
  - if [[ "$LINT" == "1" ]]; then if find . -name "*.php" -maxdepth 1 -exec php -l {} \; | grep "^[Parse error|Fatal error]"; then exit 1; fi; fi
  - if [[ "$LINT" == "1" ]]; then if find config src tests views -name "*.php" -exec php -l {} \; | grep "^[Parse error|Fatal error]"; then exit 1; fi; fi

  # Validate the xml file.
  # @link http://xmlsoft.org/xmllint.html
  - if [[ "$LINT" == "1" ]]; then xmllint --noout ./.phpcs.xml.dist; fi

  # Check coding standards. Run through composer script, to allow
  # PHP 5.2 compatibility check of main plugin file.
  - if [[ "$SNIFF" == "1" ]]; then composer phpcs; fi

  # Run tests.
  - ./vendor/bin/phpunit --testsuite unit
